package Project_Tools.Test_Fixtures is

   type Deterministic_Seed is mod 2 ** 32;
   --  Stable seed type for deterministic fixture generation.

   type Character_Range is record
      First : Character := 'a';
      Last  : Character := 'z';
   end record;
   --  Inclusive character range used by deterministic text generation.

   function Seed_Image (Seed : Deterministic_Seed) return String;
   --  Render Seed with Ada's stable modular-type image for failure messages.
   --  @param Seed Seed value to render.
   --  @return Decimal image of Seed.

   procedure Advance
     (Seed  : in out Deterministic_Seed;
      Value : out Natural);
   --  Advance Seed through project_tools' stable fixture LCG.
   --  @param Seed Mutable deterministic generator state.
   --  @param Value Bounded non-negative value derived from the updated seed.

   function Generated_Text
     (Seed           : Deterministic_Seed;
      Max_Bytes      : Natural;
      Alphabet       : Character_Range := (First => 'a', Last => 'z');
      Include_LF     : Boolean := False;
      Final_LF       : Boolean := False)
      return String;
   --  Generate deterministic in-memory fixture text.
   --  @param Seed Stable seed for the generated value.
   --  @param Max_Bytes Maximum generated bytes, including an optional final LF.
   --  @param Alphabet Inclusive range of generated non-LF characters.
   --  @param Include_LF Allow LF at deterministic interior positions.
   --  @param Final_LF Append one final LF when True and room exists.
   --  @return Deterministic text with length at most Max_Bytes.

   --  Generic temporary-directory test fixtures, shared by the version and
   --  versionlib AUnit test suites so the fixture lifecycle lives in one place.

   function Fresh_Temp_Dir (Name : String) return String;
   --  Create and return a unique temporary directory for a test case.
   --  @param Name Short label embedded in the directory name.
   --  @return Path to a freshly created, unique temporary directory.

   procedure Cleanup (Path : String);
   --  Recursively delete Path if it exists; never raises for a missing path
   --  and retries briefly to tolerate transient filesystem locks.
   --  @param Path Directory tree to remove.

   procedure Make_Directory (Path : String);
   --  Create Path (and parents) if it does not already exist.
   --  @param Path Directory to create.

   procedure Write_Text_File (Path : String; Content : String);
   --  Create or replace Path with byte-for-byte Content, creating parent
   --  directories as needed (fixture-write semantics).
   --  @param Path File to create or replace.
   --  @param Content Raw bytes to write.

   function Read_Text_File (Path : String) return String;
   --  Read Path as text, joining lines with line feeds and without a trailing
   --  line feed (fixture-content semantics).
   --  @param Path File to read.
   --  @return File contents, or propagates the I/O exception on open failure.

end Project_Tools.Test_Fixtures;
